---
- name: Ansible k8s deployment
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: prod
        api_version: v1
        kind: Namespace
        state: present
		
# Creating a Kubernetes App (service + deployment)

    - name: Create a deployment
      k8s:
        state: present
        namespace: prod
        src: deployment.yaml
